from enum import Enum as PyEnum


class Features(PyEnum):
    HR_MARK_ATTENDANCE = 0.0
    HR_PENDING_APPROVAL = 0.1
    HR_SALARY_ROLLOUT = 0.2
    HR_ADD_NEW_EMPLOYEE = 0.3
    HR_VIEW_ALL_EMPLOYEES = 0.4
    HR_APPLY_LEAVES = 0.5
    HR_MY_LEAVES = 0.6
    HR_TIMESHEET = 0.7
    HR_SHIFT_MANAGEMENT = 0.8
    HR_ADD_ANNOUNCEMENT = 0.9
